### PR TITLE
Export waypoints in formatted tracks

### PR DESCRIPTION
**Pull request by Phyks**
Hi,

This PR aims at solving https://github.com/abrensch/brouter/issues/91 by introducing a new `exportWaypoints` parameter in the server handler.

Typical implementation so far is:

```
curl "http://127.0.0.1:17777/brouter?lonlats=2.297409,48.873226|2.296593,48.873897|2.296014,48.873812&profile=trekking&alternativeidx=0&format=geojson&exportWaypoints=1"
```

```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "creator": "BRouter-1.1",
        "name": "brouter_trekking_0",
        "track-length": "221",
        "filtered ascend": "0",
        "plain-ascend": "-3",
        "total-time": "32",
        "total-energy": "2122",
        "cost": "651",
        "messages": [
          ["Longitude", "Latitude", "Elevation", "Distance", "CostPerKm", "ElevCost", "TurnCost", "NodeCost", "InitialCost", "WayTags", "NodeTags"],
          ["2297244", "48873148", "64", "16", "5350", "0", "4", "0", "0", "reversedirection=yes highway=unclassified oneway=yes", ""],
          ["2297116", "48873189", "63", "11", "3050", "0", "34", "0", "0", "highway=primary surface=sett oneway=yes", "highway=traffic_signals"],
          ["2297220", "48873365", "63", "22", "1000", "0", "0", "0", "0", "highway=unclassified surface=asphalt oneway=yes route_bicycle_lcn=yes", "nodeaccessgranted=yes highway=crossing"],
          ["2297304", "48873842", "63", "56", "1000", "0", "0", "0", "0", "highway=unclassified surface=asphalt oneway=yes route_bicycle_lcn=yes", "nodeaccessgranted=yes highway=traffic_signals"],
          ["2297302", "48873874", "63", "4", "1000", "0", "0", "0", "0", "highway=unclassified surface=asphalt oneway=yes route_bicycle_lcn=yes", "nodeaccessgranted=yes highway=crossing wheelchair=yes crossing=traffic_signals"],
          ["2297284", "48873977", "63", "12", "1000", "0", "0", "0", "0", "highway=unclassified surface=asphalt oneway=yes route_bicycle_lcn=yes", ""],
          ["2297136", "48873960", "62", "12", "3050", "0", "95", "0", "0", "reversedirection=yes highway=primary surface=paving_stones", "highway=crossing wheelchair=yes crossing=traffic_signals"],
          ["2297082", "48873954", "62", "5", "3050", "0", "0", "0", "0", "reversedirection=yes highway=primary surface=paving_stones", "highway=traffic_signals"],
          ["2296707", "48873911", "59", "28", "3050", "0", "0", "0", "0", "reversedirection=yes highway=primary surface=paving_stones", "highway=traffic_signals"],
          ["2296660", "48873906", "59", "4", "3050", "0", "0", "0", "0", "reversedirection=yes highway=primary surface=paving_stones", "highway=crossing wheelchair=yes crossing=traffic_signals"],
          ["2295960", "48873827", "58", "51", "3050", "0", "0", "0", "0", "reversedirection=yes highway=primary surface=paving_stones", ""]
        ]
      },
      "geometry": {
        "type": "LineString",
        "coordinates": [
          [2.297413, 48.873223, 63.5],
          [2.297342, 48.873179, 64.0],
          [2.297244, 48.873148, 64.0],
          [2.297116, 48.873189, 63.75],
          [2.297220, 48.873365, 63.0],
          [2.297275, 48.873518, 63.0],
          [2.297298, 48.873628, 63.25],
          [2.297311, 48.873739, 63.5],
          [2.297304, 48.873842, 63.5],
          [2.297302, 48.873874, 63.5],
          [2.297284, 48.873977, 63.5],
          [2.297136, 48.873960, 62.5],
          [2.297082, 48.873954, 62.0],
          [2.296707, 48.873911, 59.75],
          [2.296660, 48.873906, 59.5],
          [2.296591, 48.873898, 59.25],
          [2.296542, 48.873893, 59.25],
          [2.296175, 48.873851, 58.5],
          [2.296007, 48.873832, 58.25]
        ]
      }
    }
    {
      "type": "Feature",
      "properties": {
        "name": "via1",
        "type": "via",
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          2.296593,
          48.873897
        ]
      }
    }
  ]
}
```

This is only implemented for the GeoJSON formatter so far. I plan on adding support for all the other formatters as well.

@nrenner what do you think about this? Note that names for waypoints are already supported by BRouter (currently defaulting to `via1`, `via2` etc), so this could possibly be expanded further in the future.

Best,

### CODE REVIEW

**Comment by nrenner** [comment]
The GeoJSON listed above is invalid JSON, see e.g. https://jsonlint.com/:
- features array comma missing
- trailing comma in `"type": "via",`

Otherwise looks good to me.

I suppose `"type": "via"` is your own invention? Ideally there would be some standard/common way of representing waypoints in GeoJSON, but I don't know if there are apps that import/export GeoJSON with waypoints. So I guess this is fine as is.

**Comment by Phyks** [comment]
> The GeoJSON listed above is invalid JSON

Indeed, this is fixed, my bad. :/


> I suppose "type": "via" is your own invention?

It is. I kept the full track as first feature in order not to break workflows based on current BRouter GeoJSON output. For the waypoints, I do not know any standard scheme to handle it in a better way. I'll happily edit this if anyone knows a better way.

**Comment by Phyks** [comment]
This is now working for all available export formats, KML, GeoJSON and GPX.

I tried to have a coherent behavior between the different formats, looking for feedback on this!

Best,

**Comment by nrenner** [comment]
Looks good to me, but haven't tested because of the merge conflicts.

**Comment by Phyks** [comment]
I've just rebased it, conflicts should be gone.

**Pull request merged**
