### PR TITLE
BRouter translations

### PR DESCRIPTION
**Pull request by devemux86**
- English, Arabic, Catalan, Dutch, French, German, Greek, Italian, Polish, Spanish
- Move fixed strings to donottranslate-strings.xml
- Remove unused strings
- Enable app localization

There are several texts in the code that can be moved to strings.xml and translated as well.

The translations were contributed by Cruiser users:
- https://github.com/devemux86/cruiser/discussions/382

### CODE REVIEW

**Comment by afischerdev** [comment]
This breaks on git action but runs on a local gradlew build:

```
BInstallerActivity.java:174: Error: Format string 'summary_segments' is not a valid format string

<string name="summary_segments" formatted="false">Size=%s\nFree=%s</string>

```
Any idea?

**Comment by devemux86** [comment]
Interesting that there is a Lint error.

However if we do not use the `formatted="false"` then the build of release apk shows the warning:
`Multiple substitutions specified in non-positional format of string resource string/summary_segments. Did you mean to add the formatted="false" attribute?`

We better try with positional arguments.

**Comment by devemux86** [comment]
@afischerdev please run the workflow again.

Don't they run automatically after the first approval?

**Comment by afischerdev** [comment]
> or split the string.

Yes, but this one has also warnings:

`Do not concatenate text displayed with `setText`. Use resource string with placeholders.`



> Don't they run automatically after the first approval?

I've seen, but can't say why.

**Comment by devemux86** [comment]
@afischerdev please let's try again the build.

**Comment by devemux86** [comment]
@afischerdev is the Lint successful now on these changes?

**Comment by afischerdev** [comment]
@devemux86 fine now.

After merge I'll start the collection for the other hard coded strings.
I hope there are some candidates for remove.

**Comment by afischerdev** [comment]
Thank you for contribution.

**Pull request merged**
