### PR TITLE
Add new tags and description profile racebike

### PR DESCRIPTION
**Pull request by afischerdev**
Here an update for the profile `fastbike-verylowtraffic`.
About new tags and an included description.

### CODE REVIEW

**Comment by quaelnix** [comment]
This pull request increases the time needed to calculate a route (with default settings) by more than four times.

**Comment by afischerdev** [comment]
@quaelnix 
Yes, you are right. I replaced the wrong file. `racebike-verylowtraffic` was the candidate.

**Comment by quaelnix** [comment]
But isn't it a bit confusing when `fastbike-verylowtraffic.brf` and `racebike-verylowtraffic.brf` coexist?

**Comment by afischerdev** [comment]
@EssBee59 
Could you please help us in this discussion?

**Comment by EssBee59** [comment]
Hello!
As my profiles (racebike-verylowtraffic and trekking_SB) are only addressed in my test instance, I think it is not necessary to put or update them in the repository?
The current state:
I updated both profiles last month, had only few time to test but I did not found problems

**Comment by afischerdev** [comment]
@EssBee59 
Thanks for the clearing.

**Pull request closed without merging**
