### PR TITLE
Make it easier to directly run BRouter from source checkout

### PR DESCRIPTION
**Pull request by rkflx**
- Refactor/merge server.sh and local.sh
- Allow to run server.sh and server.cmd from source directory
- Update README

Test Plan:
- clone repo
- run maven
- drop rd5 into ``misc/segments4``
- launch ``./misc/scripts/standalone/server.sh``

(Note how no further configuration is necessary. In addition, compatibility with the directory structure as found in BRouter's zip archives is kept.)

### CODE REVIEW

**Comment by Phyks** [comment]
Not sure why I cannot comment directly on the diff, but on the new `local.sh`,

I think this should be `./server.sh`, isn't it? (Could also simply be a gitted symlink, but I'm not sure how this would work on Windows).

Best,

**Comment by rkflx** [comment]
> (Could also simply be a gitted symlink, but I'm not sure how this would work on Windows).

To quote the commit message (c27fa57): "By using a symlink and comparing the running script name we can avoid duplicating most of the code."

Regarding how this might work on Windows, see https://github.com/git-for-windows/git/wiki/Symbolic-Links. However, by default "Enable symbolic links" is unchecked in the installer, so indeed the link becomes a textfile, which obviously does not work. Thanks for noticing.

> I think this should be `./server.sh`, isn't it? 

This won't allow to check for `basename`, and will break calling the script from arbitrary directories again.

I'll replace the link with a script setting `BINDADDRESS` instead.

**Comment by nrenner** [comment]
I was actually thinking about moving those scripts to brouter-web, see #163.

**Comment by Phyks** [comment]
> This won't allow to check for basename, and will break calling the script from arbitrary directories again.

Indeed, but the current "server.sh" would only work if the file is in `$PATH` :) The new fix with `dirname` looks fine to me, thanks.

**Comment by Phyks** [comment]
@abrensch Would it be possible to merge this one? It would be super useful to get started hacking on BRouter I think.

Additionnally, note that the current `server.sh` file has Windows line endings, which behaves badly on Unix.

**Pull request merged**
