### PR TITLE
Add support for downloading profiles

### PR DESCRIPTION
**Pull request by jelmer**
Add support for downloading profiles. This is useful when e.g. running the standalone server in docker.

### CODE REVIEW

**Comment by abrensch** [comment]
I'm not sure what profiles you want to download. Custom-Profiles? We try to prevent this for data protection reasons. If not intended, this i sa least possivble via "../" prefixes with this patch. Or just the default profiles that are available via https://brouter.de/brouter/profiles2 ?

**Comment by jelmer** [comment]
I've got an application that interacts with my standalone brouter instance over the API. I'd like to download just regular profiles that are available on the server (but edited) - not necessarily custom ones.

**Comment by afischerdev** [comment]
The standard profiles are already checked for changes and downloaded to phone. This happens when you update your map tiles. Please see [DownloadWorker](https://github.com/abrensch/brouter/blob/18f2cb548f29ae0df6ec8b98911fbc2aebbfc2e3/brouter-routing-app/src/main/java/btools/routingapp/DownloadWorker.java#L212)

**Comment by jelmer** [comment]
> The standard profiles are already checked for changes and downloaded to phone. This happens when you update your map tiles. Please see [DownloadWorker](https://github.com/abrensch/brouter/blob/18f2cb548f29ae0df6ec8b98911fbc2aebbfc2e3/brouter-routing-app/src/main/java/btools/routingapp/DownloadWorker.java#L212)

I'm not using the app, but the standalone server in a Linux container.

**Comment by jelmer** [comment]
Closing this, since I've migrated away from brouter for my bicycle routing. If somebody else needs it feel free to pick it up.

**Pull request closed without merging**
