### PR TITLE
Update hiking profile

### PR DESCRIPTION
**Pull request by zod**
The hiking profile is quite outdated. Android users can manually get there preferred version from https://github.com/poutnikl/Brouter-profiles but it would be nice for users of brouter-web if they can use the current profile without manually uploading it.

I've used the SAC3 version because it seemed that hiking-beta was an older version of the SAC3 profile. To inform users that they should expect some smaller paths I've named it `hiking-mountain` but removed the SAC information as it might be confusing.

@poutnikl I didn't find any license information on your repository, but I guess since the profile was already used in the past you are also ok with an updated version.

@nrenner I've just had a look how brouter-web uses the profiles and noticed that renaming the profile would require updating brouter-web and all translations to remove the beta term. Should we keep the old filename?

### CODE REVIEW

**Comment by poutnikl** [comment]
The hiking-beta profile was an early beta version of what later become the profile template for all my hiking profiles that are just the generated parametrized template from the respective GitHub hiking template  project.

**Comment by nrenner** [comment]
> renaming the profile would require updating brouter-web and all translations to remove the beta term. Should we keep the old filename?

I don't mind the rename and would want to remove the ` (beta)` in any case.

**Comment by zod** [comment]
@abrensch or @nrenner
I'm not sure who has access to https://brouter.de/brouter/profiles2/ but it would be great to provide `hiking-mountain.brf` because the update mechanism of the android app fails otherwise since #426 was merged.

**Comment by afischerdev** [comment]
And I would add, may be there is a general way for publishing. eg. may be #416 comes to an end and would like see the world.

**Comment by nrenner** [comment]
@zod Done.

Just curious, do you need this for own installation from master?

> the update mechanism of the android app fails otherwise 

Shouldn't that be made more stable then?

**Pull request merged**
