### PR TITLE
Tollfree car variants

### PR DESCRIPTION
**Pull request by poutnikl**
I have modified car-fast profile by implementing avoid_tolls flag, with default avoid_tolls=false.
With the value false, the profile is fully equivalent to original profile.

I have added car-fast-tollfree profile by flipping avoid_tolls flag to true.

### CODE REVIEW

**Comment by poutnikl** [comment]
There is possible further modification to expose the flag  for Locus  dialogue toll/toll-free choice.

**Comment by poutnikl** [comment]
..also removed  the tollfree profile as redundant, being addressed by the switch.

**Comment by abrensch** [comment]
Hi Poutnik,

I have 2 issues here:

- is it possible to "extend" the comment-syntax for the Parameter defintion to what's in Lucas (pending) PR:  https://github.com/abrensch/brouter/pull/189

- At least he says that this is Locus-compatibe

In the kinamatical model, the indicator for "forbidden" is maxspeed = 0 (costfactor is just derived from that because the decoder needs it.)

Do you know if Menion is going to switch to kinematical car rooting? (ETA does not work with the traditional car-routin, as far as I know)

regards, Arndt

**Comment by poutnikl** [comment]
Ooops, some quicks with more advanced git commands, updated was overwritten by wrong pulling.

**Comment by poutnikl** [comment]
Now the car-fast.brf file is fixed.
I have modified the comments in %parameter% sections according to my understanding.

But, as far as I know, Menion has the short and long parameter descriptions hardcoded in Locus, together with localications - it may be a problem.

Currently, all 3 car related parameters ( implemented 2 years ago for my Locus-embeded car profiles ) %avoid_toll%, %avoid_unpaved%, %avoid_motoways% technically work for the car-fast.brf, I have just check the latter two if they really work in routing, but I expect they do.

I have set maxspeed for avoided unpaved to 4 km/s, not to make hard nogo way.

I have no idea if Menion is going to embed you kinetic model based profiles, but I will vote for them, they seem to me superior to my profiles.

**Comment by poutnikl** [comment]
@abrensch Do I miss anything, or the OSM tag livingstreet= in the latest car-fast.brf is missing in the lookups.dat yet ? 

As when I tested my modified profile with your recent backported updates, it failed due missing livingstreet= tag. 

Updating BRouter lookups.dat file from the master did not help. It is missing there as well.

**Comment by abrensch** [comment]
"living_street" (underscore)

Pasting github-master car-fast.brf into brouter-web does work

**Comment by poutnikl** [comment]
I see the probable mistake in copying file from my outdated fork.

**Comment by poutnikl** [comment]
Looks like good work - thanks for unpaved logic tweaks

**Pull request merged**
