### PR TITLE
Minor changes for french language

### PR DESCRIPTION
**Pull request by alkino**
The main one is `Gratuit` > `Libre`
Gratuit means free as in free beer.
Libre means free as in available place.

### CODE REVIEW

**Comment by devemux86** [comment]
@alkino

Thanks, may I ask about inserting a space before the punctuation marks?

**Comment by alkino** [comment]
Because in french this is not correct to not insert one.

https://en.wikipedia.org/wiki/History_of_sentence_spacing#French_and_English_spacing
```
French spacing inserted spaces around most punctuation marks, but single-spaced after sentences, colons, and semicolons.
```

This is really a *typographic mistake* to not add one.

**Comment by devemux86** [comment]
@alkino then is it needed a [non-breaking space](https://en.wikipedia.org/wiki/Non-breaking_space) to avoid line break with punctuation mark alone in next line?

`&nbsp;`

**Comment by alkino** [comment]
Yes, it would be better.

**Comment by afischerdev** [comment]
May be a `&#160;` could do the job.

**Comment by afischerdev** [comment]
@alkino 
Your PR has not passed the build process.
Please see [here](https://github.com/abrensch/brouter/actions/runs/9059876347/job/24986593755?pr=698#step:6:131)
Do you like to complete it?

**Pull request closed without merging**
