### PR TITLE
App: certificate fallback

### PR DESCRIPTION
**Pull request by afischerdev**
Based on #676, here is an update for the certificate problem

### CODE REVIEW

**Comment by EssBee59** [comment]
Hello Arndt.
Please remember, the current certificate expires at 21th march 2024...

Regards 
EssBee

**Comment by abrensch** [comment]
> Hello Arndt. Please remember, the current certificate expires at 21th march 2024...
> 
> Regards EssBee

thanx for the reminder. I already had a short session trying to understand how to configure "certbot" to request the long-chain variant from the LetsEncrypt API, will resume shortly (currently short of time). Documentation is rare, seems to be an exotic topic. Will have to continue with the short-chain certificate if I do not succeed.

**Comment by EssBee59** [comment]
Arndt,

I agree, 3 monthes validity is too short, but it seems not possible to request a longer time.
(example https://community.letsencrypt.org/t/how-to-set-expiration-date/79440)

**Comment by abrensch** [comment]
> Please remember, the current certificate expires at 21th march 2024...

Did the renewal now manually and seems to work ok

Command to obtain the full-chain cert was:

 certbot certonly --preferred-chain "DST Root CA X3"

However, I cannot test the original issue with the Android <=6 phones

Will have to do the manual renewal two times more, in order to get the last full-chain cert end of june with validity end of september

**Pull request merged**
