### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by arturhooks5**
added the command for downloading segments

### CODE REVIEW

**Comment by polyscias** [comment]
I am wondering what is the use case for downloading all segments.

brouter is not good for long routes and normally only one segment is enough unless you live on the edge of segments.

**Comment by arturhooks5** [comment]
I'm using brouter on my website - so I want to update all earth by cronjob. That's the case.

**Comment by arturhooks5** [comment]
@poutnikl In my case, I'm updating segments every 6 months... Ofc if somebody wants to kill the source server, I can't stop them and I don't think that adding or deleting such script can avoid it.
Maybe I should add downloading in the one stream by default.

**Comment by polyscias** [comment]
Understood, for running a brouter-web server having all segments makes sense.

Still I think it is not wise to add this patch, whoever is using brouter on a website should know how to do this and adding it to README.md will enable people without a need to execute this. How about dropping this PR?

**Comment by arturhooks5** [comment]
@polyscias, if my case is so rare maybe you are right and you should drop it

**Comment by polyscias** [comment]
That are not that many people that run their own brouter server on their website I am sure.

Like written, I find the risk that incorporating the command in the README triggers people who not really need it to execute a full download while people that need it should be smart enough to find it themselves.

**Pull request closed without merging**
