### PR TITLE
Update for Android 11 part 1

### PR DESCRIPTION
**Pull request by afischerdev**
This update has some parts for the move to Android 11

- change the inferface #314
- change main folder .../Android/media/btools.routingapp/
- has an own import folder for files like favorites or nogo* gpx
- export json #246
- update all tiles #306
- hardcoded speed #301
- black screen #286

still pending
- new icon brouter-web [286](https://github.com/nrenner/brouter-web/issues/286)
- refreshed profiles
- Android watchdog #277 - no error results during testing
- download manager #271 - no error results during testing
- download rd5 in background #227
- update for lookups.dat and profiles over the air

others
- git workflow: is there someone how can do the move to gradle? I've never done it and doesn't have a test environment.

This version is based on the idea other apps use the interface with a 'pathToFileResult' set to null - so the result comes back as string.
It is still possible to use the interface file driven - in Android 10+. But only if the result path is inside the .../Android/media/btools.routingapp/.. folder. This means to other apps using BRouter file export they have to deal with the Android storage access framework via a document url.

### CODE REVIEW

**Comment by EssBee59** [comment]
> * git workflow: is there someone how can do the move to gradle? I've never done it and doesn't have a test environment.

Hello!
I am not really expert for maven / gradle, but I try to help ...
For my understanding:
Is your test version "brouter-test-and11" compiled with maven or gradle?

I dowloaded the zip file on my windows and could build the app using gradlew (manually) or android-studio.
So, I think, without maven?

The only real problem I had was  with the java (jar) version for using with the brouter-web:
To get it running, I had to change the build.gradle of brouter-server and the start commands.

**Comment by afischerdev** [comment]
Yes, all was build with gradlew.
I add a task 'fatJar' to build the server/mapbuilder jar with depending classes.

**Comment by EssBee59** [comment]
Thank for the info!
I could not find the task "fatjar" but I assume, you have currently no problem /question to gradle or fatjar.  (my brouter fatjar, built with gradle, is running well) 
regards

**Comment by afischerdev** [comment]
I'll add this to the readme next update.

**Pull request merged**
