### PR TITLE
Replace multiple occurrences of toLowerCase()

### PR DESCRIPTION
**Pull request by moving-bits**
Avoids recalculation of `toLowerCase()` for every branch in `addLookupValue()`

### CODE REVIEW

**Comment by afischerdev** [comment]
Thank you for contributing

**Comment by quaelnix** [comment]
> Thank you for contributing

Yes, but does this really improve the performance (and or readability) of the code?

**Comment by moving-bits** [comment]
> > Thank you for contributing
> 
> Yes, but does this really improve the performance (and or readability) of the code?

Readability IMHO yes (but that's partly a matter of personal preference), and performance depends on which switch branch gets called.

**Comment by afischerdev** [comment]
From my point of view I can't see much more readability here `valueLowerCase vs value.toLowerCase`.
The benefit I see is the single call of the function.
And may be an other one for the call with `Locale.US` - when this is using an ASCII and not an UTF16 variant.

But the longer I look at this code, I see another optimization:
- move the call value.toLowerCase a few lines up to the 'value prepare section'.
- stay with the name `value`
- remove the trim() calls - blanks have been escaped with '_' and that was removed in 'value prepare section'
- may be add a remove for non breaking space

I'll do that the next days.

**Pull request merged**
