### PR TITLE
Update the APK for multiple issues

### PR DESCRIPTION
**Pull request by afischerdev**
For some issues there are a few minor changes:

- NullPointerException on VoiceHintProcessor #603
- NullPointerException on ServiceModeConfig, reported from Play Store
- IllegalStateException on RoutingParameterDialog, reported from Play Store
- Monochrome icon #597

### CODE REVIEW

**Comment by quaelnix** [comment]
https://github.com/abrensch/brouter/blob/8ae614cfa4631abc65fbdcb00e506a52c0d34d8c/brouter-routing-app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml#L5
https://github.com/abrensch/brouter/blob/8ae614cfa4631abc65fbdcb00e506a52c0d34d8c/brouter-routing-app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml#L5
Can we really simply reuse `ic_launcher_foreground`?

**Comment by afischerdev** [comment]
Looks like this:
icons

**Comment by afischerdev** [comment]
@rkflx 
Merge and go on or do you like to finish the #457 first?

**Comment by afischerdev** [comment]
@rkflx 
When I wrote this I think I remembered you are a friend of git driven version numbers. And may be you like something to do in that direction.

**Pull request merged**
